load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//src:__subpackages__"])

cc_library(
    name = "audio_effect_peak_limiter",
    srcs = ["audio_effect_peak_limiter.c"],
    hdrs = ["audio_effect_peak_limiter.h"],
    deps = [
        "//include",
        "//src/common",
    ],
)

cc_library(
    name = "oar_limiter",
    srcs = ["oar_limiter.c"],
    hdrs = ["oar_limiter.h"],
    deps = [
        ":audio_effect_peak_limiter",
        "//include",
        "//src/common",
    ],
)

